id: AF71716AE
base_file: f1EAA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:15:51.162067
  last_modified_at: 2022-06-11 13:15:51.162125
