id: AF71716AE
base_file: f7645.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:15:51.169587
  last_modified_at: 2022-06-11 13:15:51.169596
